### ISSUE TITLE
How to exclude mobile browsers from the result? 

### ISSUE THREAD

**Issue by jitendravyas** [ai/browserslist#131]
This is not working `last 2 versions not mobile` here http://browserl.ist/?q=last+2+versions+not+mobile

**Comment by ai** [comment]
1. `not` is a separated query, not modifier. So it will be `last 2 version, not IE 11`
2. There is not `mobile` query.

**Comment by ai** [comment]
Why you want to exclude mobile browsers? Even if you have no special mobile version, mobile users stiill could open desktop version.

This is a reason why we have no `mobile` query right now.

**Comment by jitendravyas** [comment]
I want to exclude mobile browser because we are making a fixed width web app which makes sense for desktop users only.

**Comment by ai** [comment]
We Exclude it name by name. I don’t want to add shortcut for it, because it is very bad practice. Web should be accessible for mobile users too — there is many poor people without PC and only with cheap Android.

**Comment by atomicpages** [comment]
@ai a pragmatic usage of targeting desktop clients can be seen in enterprise applications &mdash; my 2c

**Comment by ai** [comment]
@atomicpages “enterprise” is not an answer. Any enterprise user has a smartphone. Sometimes local network doesn’t work. Sometimes they are on the lunch during an emergency call. I don't see a popular reason why users should not open a website from a phone.

(Technically, I see 0.01% of the reasons, like use USB-A OTP-keys, but you can always specify browsers manually. API should force good solution and block bad solution. Any enterprise solution will win in terms of money with some simple mobile support, even without special media queries. So what is a reason to create a API to force developers to reduce money for customers?)

**Comment by rDr4g0n** [comment]
While I would LOVE to support mobile devices for every enterprise web app I build, that is often a low priority when building apps designed to be displayed on giant screens in a NOC, or for exploring complex datasets, or editing dashboards, or viewing and managing giant node graphs. This doesn't even get into security issues with enterprises who only allow their apps to be accessed internally. While I agree that mobile should be better supported in most of my enterprise apps, I don't make those decisions. I suspect there are a lot of developers out there in a similar position.

I don't think we should try to answer a question about the strategic decision to support mobile or not (product development is insanely complex, how can we accurately answer that question?). I think the question is better simplified to whether or not there is a legitimate distinction between desktop and mobile browsers, and if that distinction should be queryable with browserslist.

**Comment by ai** [comment]
Remove it one by one. It is a bad behavior and should not be sorted by syntax sugar. Sugar only for good kids 😄.

**Comment by awexfwex** [comment]
Flip-side, I'm trying to build for mobile only. This seems like an implementation decision you should be leaving up to us. I have writed code b4.

**Comment by danpantry** [comment]
@ai I create internal enterprise applications that will never be accessible via mobile. Preventing me from excluding mobile means that my transpiler will attempt to compile code for mobile browsers - which can make reading stack traces more challenging since it will, for example, replace async/await with so-called 'helpers'

I don't really think it is your prerogative to assume what the audience of the users of your library serve

**Comment by ai** [comment]
@danpantry I see two options here:

1. I am adding some `not mobile` query. You with 10+ developers are a little happy (because it is syntax sugar you can still ignore mobile with long query). 10 000+ people are not really happy (instead of your case, the website will not work on mobile devices and they will not have any option to avoid this problem compare to you), because other bad developers will use `not mobile` on the wrong case.
2. I still keeping API from adding this query. You are a little unhappy (you still can ignore mobile browsers by name). 10 000+ people are happy because they are not cut from the global world (a lot of people have only a mobile phone).

Yeap, I know that we are all put our wishes above. And I understand that syntax sugar with one `not mobile` query is always better than long config. 

But this is a good example of a hard choice. When few people should suffer to protect others. I think it is a good deal since you still can remove mobile browsers, Just list them by the name `not android > 0, …`.

If you want, you can create a sharable Browserslist config with this list. https://github.com/browserslist/browserslist#shareable-configs

**Comment by ai** [comment]
You can remove browsers by name `not X > 0`. You can even create a sharable config with all mobile browsers.

> Interestingly enough my current request for a is mobile query is actually to increase compatibility and UX by [showing a warning to the user for optimal usability of a service](https://user-images.githubusercontent.com/14975046/196461728-82f60800-e610-497c-adc6-5e926ef46ea2.png). But showing that we support Android versions to someone on a desktop machine makes no sense and is just confusing.

This warning is a bad practice. Android app is not a replacement for an adaptive design by `@media`.

**Comment by skjnldsv** [comment]
> This warning is a bad practice. Android app is not a replacement for an adaptive design by `@media`.

Who said I'm redirecting to an android app?
Preventing using outdated and/or neglected browsers is always good practice. From UX but also security.

Showing what alternative the user have is even  better. Which is what I'm trying to achieve here :)

**Comment by ai** [comment]
> Excluding mobiles from this list if the user is on a desktop (and vice versa, showing mobile brosers only if the user is on a mobile) is what I'm trying to achieve.

Separated desktop and mobile versions is a bad practice. You should have single website with `@media` in CSS and JS.

But if you really want it, you should not target browser user agent for this warning, but use screen width.

**Comment by skjnldsv** [comment]
> Separated desktop and mobile versions is a bad practice. You should have single website with `@media` in CSS and JS.

You're missing the point. We are fully compliant to screen size with media queries.
Let me give you an example flow and then I'll stop because I feel like I'm just polluting this issue with my specific use case.
You use IE10, you try to use Nextcloud (software in question)
1. You get redirected, we do NOT support ie for security and compliance reasons
2. A message guides you towards a more fitting browser.

Now, if the user is on desktop, showing a message saying, "Hey, please use Chrome , Firefox, Chrome for Android or Safari for iOS instead"  is bad UX and not helping, especially if they're not at ease with technology.
Showing appropriate message like
1. If the user is on a mobile device: "Hey, please use Chrome for Android or Safari for iOS instead"
2. Or if they are on a desktop machine: ""Hey, please use Chrome or Firefox"

This leads to a more appropriate workflow and much better understanding of the end user usage

Hope I could help in any way. You're the one that makes the decision in the end, this lib is in a monopoly situation. I hope browserslist can be bit more open to external ideas or direction like this ticket  in the future :wink: . Cheers! :sun_with_face: :hugs:

**Comment by ai** [comment]
> If the user is on a mobile device: Hey, please use Chrome for Android or Safari for iOS instead
> Or if they are on a desktop machine: Hey, please use Chrome or Firefox

It is better to use media query to switch between these messages.

Browserslist will give you an allow-list of user-agents, but what if user uses some unknown browser?

**Comment by skjnldsv** [comment]
>  but what if user uses some unknown browser?

How can you ensure you will ship compatible javascript with that browser? You cannot :confused: 
Unknown browser will get a warning and the user can then decide if they're ok continuing like this. But if bugs or glitches occurs, they will know why it happens. 

> It is better to use media query to switch between these messages.

Screen size is different than the platform. I have narrow screens and windows. That doesn't mean I'm on a mobile.
That does mean the UI needs to adjust, but that is a UI issue, not a UX. So this is not relevant at all with javascript compatibility here.

**Comment by celluj34** [comment]
I need a "not mobile" query because I'm working on an excel add-in using javascript. We do not support users using mobile browsers in excel online, therefore I want to exclude mobile browsers.

**Comment by alexpirine** [comment]
We have specific software for people using their smartphones only (technicians and salesmen working in the field, they don't even have a laptop), and we have other software mainly used on desktop (people in the office receiving customer calls, insuring customer service).

We would LOVE to improve mobile browsers compatibility for the first, and prefer desktop compatibility for the other, while still preserving a reasonable bundle size.

Would it be possible to have a query that says "cover 99% of mobile browsers"?

**Comment by ai** [comment]
> Would it be possible to have a query that says "cover 99% of mobile browsers"?

Create a [sharable Browserslist config](https://github.com/browserslist/browserslist#shareable-configs) and then use:

```
cover 99% and extends browserslist-config-mobile
```
