### ISSUE TITLE
last 3 ChromeAndroid versions gives only last version of Chrome Android not last 3

### ISSUE THREAD

**Issue by jitendravyas** [ai/browserslist#156]
http://browserl.ist/?q=last+3+ChromeAndroid+versions

**Comment by ai** [comment]
Yeap, it is confusing. But this is how Can I Use database works — we can’t change it.

Can I Use contains only data about latest Chrome Android version.

But I have good things:

1. There is no sense to select `last 3 versions` of Chrome Android, because anyway, Autoprefixer will use only latest version too. Autoprefixer and all other tools use Can I Use database. And this database contains data only about latest Chrome Android. So even if you select 3 versions, Autoprefixer will add prefixes only for latest.
2. Chrome Android is equal to desktop Chrome in most of the cases. So if you select `last 3 chrome versions, last 1 ChromeAndroid version` it will generate prefixes for 3 last Chrome Android version too (because they need same prefixes as desktop Chrome).

**Comment by kanongil** [comment]
Why is this not a bug?

http://browserl.ist/?q=ChromeAndroid+%3E%3D+33

When used with babel-preset-env, the generated javascript is unusable on old devices.

**Comment by ai** [comment]
@kanongil Can I Use data contains only one latest `ChromeAndroid`. If you know any solution, I am open for suggestions

**Comment by Grawl** [comment]
I have many issues in Sentry logs showing me that there is many clients with Android phones from 2017, so I have to fix them somehow

**Comment by rhaksw** [comment]
@Grawl did you ever find a solution for clients with old Android phones or outdated versions of Chrome? I'm guessing the answer is no. Some of my site's users mentioned it to me [here](https://www.reddit.com/r/reveddit/comments/1056jdt/reveddit_does_not_work/j3c314f/?context=3).

**Comment by Grawl** [comment]
@rhaksw not yet
