### ISSUE TITLE
differentiating mobile and desktop

### ISSUE THREAD

**Issue by Announcement** [ai/browserslist#184]
Whilst this is generally a bad idea for the initial purpose of the package, it would be nice to differentiate **mobile** and **desktop** browser usage.

If there is already a way please **document** it.

This would be nice for research purposes, for example the reason I needed this was to see what percent of the sample is using **IE11** in response to a question on [freenode](irc.freenode.net)

**Comment by ai** [comment]
Here is big thread: https://github.com/ai/browserslist/issues/131

Short answer: in most of the cases creating mobile-only/desktop-only website is a mistake, which will lose money for the customer. API should protect the developer from making mistake.

If it will be a really unique 0.01% case when you have a reason, you can always specify browsers by name. But we should not have a shortcut because it will force 5% of developers to make a mistake. 0.01% of extra 50 symbols is a good cost for not having 5% of mistakes.
