### ISSUE TITLE
Relative "since" query

### ISSUE THREAD

**Issue by wopian** [ai/browserslist#208]
https://github.com/ai/browserslist/pull/189 added the `since <year>` query which supports absolute years (i.e `2013`) 🎉 

Could the `since` query be expanded to support `since last <number> years` to target browsers without a hard-coded value like the `last <number> versions` query?

Edit: `last <number> years` may be a better query

**Comment by awkaiser** [comment]
Agreed, [`last 3 years, not < 1%`](http://browserl.ist/?q=since+2015%2C+not+%3C+1%25) would be more useful than providing a static year.

@wopian Would you like to try creating a pull request? You could reference the current [`since`](https://github.com/ai/browserslist/blob/c32316d204c9a17e570962dec6b5abdfd39a2e24/index.js#L583-L600) implementation as a starting point. (Don't forget to include [tests!](https://github.com/ai/browserslist/blob/c32316d204c9a17e570962dec6b5abdfd39a2e24/test/since.test.js))

**Comment by ai** [comment]
`last X years` was released in 2.11.
