### ISSUE TITLE
Change default browsers

### ISSUE THREAD

**Issue by ai** [ai/browserslist#218]
I decided that any big changes in Browserslist should be approved by >50% Browserslist users.

Suggestions:

1. Add `not dead` query to default browsers. It is a new query of dead browsers. Dead browser is a browser with less than 1% global market share and no security updates or no new minor/patch releases for last 12 month. IE 10 will be a dead browser. Maybe Blackberry browser as well. I will maintain the list of dead browsers manually.
2. Decrease market share limit from `>1%` to `>0.5%`. It will add `android 4.4`, `chrome 61`, `chrome 49`, `ios_saf 10.0-10.2`, `ios_saf 9.3`. The most important here is `chrome 49`, because it is the last Chrome with Windows < 7 support.

What do you think? Are you agree with this changes?

- [x] Autoprefixer @ai
- [x] Babel @yavorsky
- [x] postcss-preset-env @jonathantneal
- [x] postcss-normalize @jonathantneal
- [ ] eslint-plugin-compat @amilajack
- [x] stylelint-no-unsupported-browser-features @ismay

**Comment by yavorsky** [comment]
Looks reasonable to me! I think extending query is a good way because then we could fit more needs. At the same time, it won't add some complexity, because browserslist queries are understandable w/o diving into any additional API/docs.

> I will maintain the list of dead browsers manually.
>no new minor/patch releases for last 12 month
Seems like this could be automated. Otherwise, it would be really hard to maintain all targets w/o security updates or released and after 2-3 months I would expect irrelevant data.

The only concern for me is additional complexity. But as I said before, we should distinguish complexity from additional flexibility. I like the idea add some new **clear** and **intuitive** options. 👍

**Comment by ismay** [comment]
Sounds good to me, I'm on board 👍

**Comment by jonathantneal** [comment]
Yes, I approve of this, and I’ve really wanted something like this. Right now, I’m using a long selector on [the postcss-preset-env page](https://jonathantneal.github.io/postcss-preset-env/) to accomplish something similar:

```
last 3 chrome versions, last 3 edge versions, last 3 firefox versions, last 3 safari versions, last 3 ios versions, last 3 android versions
```

Big 👍 from me.

**Comment by ai** [comment]
We got 50%. Now I will wait few days for thoughts from the community. On next week we will have 3.0 release. Be ready to release minor/patch (or major, depends on you) version with new Browserslist.

@yavorsky will we able to use Browserlist 3 in Babel 7? Maybe update Browserslist in Babel 6 too?

**Comment by yavorsky** [comment]
@ai 
>will we able to use Browserlist 3 in Babel 7?

Sure, we are always open to updating `browserslist`.

>Maybe update Browserslist in Babel 6 too?

Currently, we are focused on the 7, but we also trying to keep some things (compat-table, browserslist) fresh for the stable.

**Comment by meduzen** [comment]
Yo! Community user here. I always use a custom `browserslist` file in my `scss`folder, and I love both ideas, especially the `not dead` query that can be good for some projects. Also, lowering the minimal browser market share to 0.5% is also a good move to the browser diversity/indulgence, because 1% makes you probably skip a lot of users in some countries.

**Comment by ai** [comment]
Notice about other 3.0 changes:

* `BlackBerry 10` and `BlackBerry 7` will be added as dead browsers as well.
* I plan to remove `>1% in US` queries support in a client-side version of Browserslist. Country usage statistics takes 155 KB in the bundle and used very rarely. It will be still possible to use country statistics by `stats: require('caniuse-lite/…')`

**Comment by Grawl** [comment]
I am now using iPhone 4 and it's ok to browse internet but it requires "ios 7" in Browserslist to enable to use `flex`.

**Comment by ai** [comment]
3,0 was released. Let’s update dependencies in our project (I will release a major update for Autoprefixer, but it is up to you).

**Comment by yavorsky** [comment]
Updated for babel https://github.com/babel/babel/pull/7365

**Comment by ai** [comment]
Autoprefixer master started to use Browserslist 3.0 as well. Will release it in next week.
